export { default as HeaderComponent } from "../organisms/HeaderComponent.vue"
export { default as PresentationMain } from "../organisms/PresentationMain.vue"
export { default as ServicesProvided } from "../organisms/ServicesProvided.vue"
export { default as ContainerGloba } from "../bosons/ContainerGloba.vue"
export { default as HomePage } from "../templates/PageHome.vue"
